"use client";

import Image from "next/image";
import React, { useEffect, useState } from "react";
import ScreenshotSlider from "@/components/ScreenshotSlider";
import StickyCta from "@/components/StickyCta";
import { links } from "@/lib/links";
import { trackEvent } from "@/lib/analytics";

const slides = [
  { src: "/screenshots/app-dashboard.png", alt: "eKasiBooks dashboard overview" },
  { src: "/screenshots/invoices-list.png", alt: "Invoice list and payment tracking in eKasiBooks" },
  { src: "/screenshots/invoice-preview.png", alt: "Invoice PDF preview generated by eKasiBooks" },
  { src: "/screenshots/quotes-list.png", alt: "Quotes management screen in eKasiBooks" },
  { src: "/screenshots/customers-list.png", alt: "Customer list and contact records in eKasiBooks" },
  { src: "/screenshots/reports-dashboard.png", alt: "Reports and insights dashboard in eKasiBooks" },
  { src: "/screenshots/settings.png", alt: "Settings and preferences screen in eKasiBooks" },
  { src: "/screenshots/delivery-note-preview.png", alt: "Delivery note preview created in eKasiBooks" },
];

function ZoomableImage({
  src,
  alt,
  hint = "Click to zoom • Esc to close",
}: {
  src: string;
  alt: string;
  hint?: string;
}) {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    if (!open) return;

    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };

    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";

    window.addEventListener("keydown", onKeyDown);
    return () => {
      window.removeEventListener("keydown", onKeyDown);
      document.body.style.overflow = prevOverflow;
    };
  }, [open]);

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        aria-label="Zoom image"
        title={hint}
        style={{
          all: "unset",
          cursor: "zoom-in",
          display: "block",
          width: "100%",
        }}
      >
        <Image
          src={src}
          alt={alt}
          width={1400}
          height={900}
          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 90vw, 1200px"
          style={{ width: "100%", height: "auto", display: "block" }}
          priority={src === "/screenshots/app-dashboard.png"}
        />
      </button>

      {open ? (
        <div
          role="dialog"
          aria-modal="true"
          onClick={() => setOpen(false)}
          style={{
            position: "fixed",
            inset: 0,
            zIndex: 9999,
            background: "rgba(0,0,0,.72)",
            display: "grid",
            placeItems: "center",
            padding: 12,
            cursor: "zoom-out",
            animation: "zoomFade .14s ease-out",
          }}
        >
          <div
            onClick={(e) => e.stopPropagation()}
            style={{
              maxWidth: 1100,
              width: "min(1100px, 96vw)",
              maxHeight: "92vh",
              background: "#fff",
              borderRadius: 14,
              overflow: "hidden",
              boxShadow: "0 18px 70px rgba(0,0,0,.35)",
              border: "1px solid rgba(255,255,255,.10)",
              display: "grid",
              gridTemplateRows: "auto 1fr",
              cursor: "default",
            }}
          >
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                padding: 8,
                borderBottom: "1px solid rgba(0,0,0,.06)",
                background: "#fff",
              }}
            >
              <span style={{ fontWeight: 900, fontSize: 12.5, color: "#0d2030", opacity: 0.85 }}>{hint}</span>
              <button
                type="button"
                onClick={() => setOpen(false)}
                aria-label="Close"
                style={{
                  border: "1px solid rgba(0,0,0,.10)",
                  background: "#fff",
                  borderRadius: 10,
                  padding: "7px 9px",
                  fontWeight: 900,
                  cursor: "pointer",
                }}
              >
                ✕
              </button>
            </div>

            <div style={{ overflow: "auto", background: "#f7f9fc" }}>
              <Image
                src={src}
                alt={alt}
                width={1400}
                height={900}
                sizes="100vw"
                style={{ width: "100%", height: "auto", display: "block" }}
              />
            </div>
          </div>
        </div>
      ) : null}
    </>
  );
}

export default function HomeClient() {
  useEffect(() => {
    const items = document.querySelectorAll(".reveal");
    items.forEach((el, i) => {
      setTimeout(() => el.classList.add("show"), i * 110);
    });
  }, []);

  return (
    <main>
      <div
        className="sectionTight"
        style={{
          marginBottom: 0,
          position: "relative",
          zIndex: 2,
        }}
      >
        <div
          className="container"
          style={{
            textAlign: "center",
            paddingTop: 10,
            paddingBottom: 18,
          }}
        >
          <span className="announcement">
            Now on Windows &amp; macOS <small>• Works offline after sign-in • VAT-ready • WooCommerce sync</small>
          </span>
        </div>

        <div
          aria-hidden
          style={{
            position: "absolute",
            left: 0,
            right: 0,
            bottom: -1,
            height: 26,
            background: "linear-gradient(to bottom, rgba(255,255,255,0.9), rgba(255,255,255,0))",
            pointerEvents: "none",
          }}
        />
      </div>

      <section
        className="homeHero"
        style={{
          paddingTop: 61,
          paddingBottom: 56,
          background:
            "radial-gradient(1000px 600px at 10% 0%, rgba(255,255,255,.14), transparent 60%), linear-gradient(135deg, var(--brand-700) 0%, var(--brand) 100%)",
        }}
      >
        <div className="container" style={{ maxWidth: 1200 }}>
          <div
            className="heroGrid"
            style={{
              display: "grid",
              gridTemplateColumns: "1.05fr .95fr",
              gap: 40,
              alignItems: "center",
            }}
          >
            <div>
              <h1
                className="reveal heroTitle"
                style={{
                  margin: 0,
                  color: "#fff",
                  fontWeight: 900,
                  letterSpacing: "-0.03em",
                  lineHeight: 1.12,
                  fontSize: 40,
                }}
              >
                Create invoices, manage customers, and sync WooCommerce products in one simple app.
              </h1>

              <p
                className="reveal heroSubtitle"
                style={{
                  marginTop: 16,
                  marginBottom: 0,
                  color: "rgba(231,243,244,.95)",
                  fontSize: 15.5,
                  lineHeight: 1.6,
                  maxWidth: 620,
                }}
              >
                Create branded quotes, convert them to invoices, track payments, and keep your business data organised —
                with VAT support, local backups, offline use after sign-in, and WooCommerce integration for stores that
                need accounting and sales in one flow.
              </p>

              <div
                className="reveal"
                style={{
                  display: "flex",
                  gap: 10,
                  flexWrap: "wrap",
                  marginTop: 18,
                }}
              >
                <a
                  href={links.portalRegister}
                  onClick={() => {
                    trackEvent("cta_click", {
                      label: "register",
                      location: "hero",
                      page: window.location.pathname,
                    });
                  }}
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    justifyContent: "center",
                    borderRadius: 999,
                    padding: "8px 12px",
                    fontWeight: 900,
                    fontSize: 14,
                    textDecoration: "none",
                    background: "#fff",
                    color: "var(--ink)",
                    border: "1px solid rgba(255,255,255,.22)",
                    boxShadow: "0 14px 34px rgba(0,0,0,.20)",
                    transition: "transform .2s ease, box-shadow .2s ease",
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.transform = "translateY(-2px)";
                    e.currentTarget.style.boxShadow = "0 20px 52px rgba(0,0,0,.24)";
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.transform = "translateY(0)";
                    e.currentTarget.style.boxShadow = "0 14px 34px rgba(0,0,0,.20)";
                  }}
                >
                  Create Free Account
                </a>

                <a
                  href={links.pricing}
                  onClick={() => {
                    trackEvent("cta_click", {
                      label: "pricing",
                      location: "hero",
                      page: window.location.pathname,
                    });
                  }}
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    justifyContent: "center",
                    borderRadius: 999,
                    padding: "8px 12px",
                    fontWeight: 900,
                    fontSize: 14,
                    textDecoration: "none",
                    background: "rgba(255,255,255,.08)",
                    color: "#fff",
                    border: "1px solid rgba(255,255,255,.22)",
                    transition: "transform .2s ease, background .2s ease",
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.transform = "translateY(-2px)";
                    e.currentTarget.style.background = "rgba(255,255,255,.12)";
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.transform = "translateY(0)";
                    e.currentTarget.style.background = "rgba(255,255,255,.08)";
                  }}
                >
                  See Pricing
                </a>
              </div>

              <div
                className="reveal"
                style={{
                  marginTop: 10,
                  color: "rgba(255,255,255,.88)",
                  fontSize: 12.5,
                  fontWeight: 800,
                  letterSpacing: ".01em",
                }}
              >
                Create your account in under 2 minutes • No credit card required
              </div>

              <div
                className="reveal"
                style={{
                  marginTop: 14,
                  display: "flex",
                  gap: 8,
                  flexWrap: "wrap",
                  alignItems: "center",
                }}
              >
                {[
                  "Built in South Africa",
                  "Your logo & colours",
                  "PDF export",
                  "Local backups",
                  "Customer statements",
                  "WooCommerce sync",
                ].map((t) => (
                  <span
                    key={t}
                    style={{
                      display: "inline-flex",
                      alignItems: "center",
                      padding: "7px 10px",
                      borderRadius: 999,
                      background: "rgba(255,255,255,.10)",
                      border: "1px solid rgba(255,255,255,.18)",
                      color: "rgba(255,255,255,.92)",
                      fontWeight: 900,
                      fontSize: 11.5,
                      letterSpacing: ".02em",
                    }}
                  >
                    {t}
                  </span>
                ))}
              </div>
            </div>

            <div className="reveal" aria-label="eKasiBooks App UI preview">
              <div
                style={{
                  borderRadius: 18,
                  border: "1px solid rgba(255,255,255,.16)",
                  background: "rgba(255,255,255,.08)",
                  boxShadow: "0 22px 68px rgba(0,0,0,.28)",
                  padding: 12,
                }}
              >
                <div
                  style={{
                    borderRadius: 14,
                    overflow: "hidden",
                    background: "#fff",
                    border: "1px solid rgba(0,0,0,.06)",
                  }}
                >
                  <ZoomableImage
                    src="/screenshots/app-dashboard.png"
                    alt="eKasiBooks dashboard screenshot showing totals and quick actions"
                  />
                </div>

                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    gap: 10,
                    marginTop: 10,
                    flexWrap: "wrap",
                  }}
                >
                  <span style={{ color: "rgba(255,255,255,.9)", fontWeight: 900, fontSize: 11.5 }}>
                    Desktop app • Offline after sign-in • WooCommerce-ready
                  </span>
                  <a
                    href={links.features}
                    onClick={() => {
                      trackEvent("cta_click", {
                        label: "features",
                        location: "hero_secondary",
                        page: window.location.pathname,
                      });
                    }}
                    style={{
                      color: "rgba(255,255,255,.95)",
                      fontWeight: 950,
                      fontSize: 11.5,
                      textDecoration: "none",
                      borderBottom: "1px solid rgba(255,255,255,.35)",
                    }}
                  >
                    Explore features
                  </a>
                </div>
              </div>
            </div>
          </div>

          <style>{`
            @media (max-width: 992px){
              .heroGrid{
                grid-template-columns: 1fr !important;
                gap: 22px !important;
              }
            }

            @media (max-width: 600px){
              .homeHero{
                padding-top: 44px !important;
                padding-bottom: 44px !important;
              }
              .heroTitle{
                font-size: 31px !important;
                line-height: 1.1 !important;
                letter-spacing: -0.02em !important;
              }
              .heroSubtitle{
                font-size: 14px !important;
                line-height: 1.6 !important;
              }
            }

            @media (max-width: 380px){
              .heroTitle{
                font-size: 28px !important;
              }
            }
          `}</style>
        </div>
      </section>

      <section className="section" style={{ paddingTop: 52, paddingBottom: 18 }}>
        <div className="container" style={{ maxWidth: 1200 }}>
          <div
            className="benefitsGrid reveal"
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
              gap: 16,
            }}
          >
            {[
              { title: "Professional docs", icon: "🧾", desc: "Clean quotes & invoices with your logo and VAT details." },
              { title: "Offline-ready", icon: "🔌", desc: "Sign in once, then quote and invoice even without internet." },
              { title: "WooCommerce sync", icon: "🛒", desc: "Connect your store and bring WooCommerce sales into your workflow." },
            ].map((b) => (
              <div
                key={b.title}
                className="cardLift"
                style={{
                  background: "#fff",
                  border: "1px solid var(--ring)",
                  borderRadius: 16,
                  padding: 18,
                  boxShadow: "0 10px 28px rgba(10,37,64,.08)",
                }}
              >
                <div style={{ fontWeight: 950, color: "var(--ink)" }}>
                  <span style={{ marginRight: 8 }}>{b.icon}</span>
                  {b.title}
                </div>
                <p className="muted" style={{ marginTop: 8, marginBottom: 0, lineHeight: 1.6 }}>
                  {b.desc}
                </p>
              </div>
            ))}
          </div>

          <style>{`
            @media (max-width: 992px){
              .benefitsGrid{
                grid-template-columns: 1fr !important;
              }
            }
          `}</style>
        </div>
      </section>

      <section className="section" style={{ paddingTop: 18, paddingBottom: 22 }}>
        <div className="container" style={{ maxWidth: 1200 }}>
          <div
            className="reveal"
            style={{
              background: "var(--card)",
              borderRadius: 16,
              padding: 22,
              border: "1px solid var(--ring)",
              boxShadow: "0 10px 28px rgba(10,37,64,.08)",
              overflow: "hidden",
              position: "relative",
            }}
          >
            <div
              aria-hidden
              style={{
                position: "absolute",
                inset: "auto -180px -180px auto",
                width: 320,
                height: 320,
                background: "radial-gradient(circle, rgba(33,93,99,.16), transparent 70%)",
                borderRadius: 999,
              }}
            />

            <h2 className="h2" style={{ margin: 0 }}>
              Built for South Africa
            </h2>
            <p className="muted" style={{ marginTop: 10, marginBottom: 0, maxWidth: 860, lineHeight: 1.6 }}>
              Most accounting tools are built overseas and adapted later. eKasiBooks is built locally, with South African
              small businesses as the primary market — simple, practical, VAT-ready, and flexible enough for modern
              businesses selling both offline and online.
            </p>

            <div
              className="saGrid"
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(3, minmax(0,1fr))",
                gap: 14,
                marginTop: 16,
              }}
            >
              {[
                { t: "VAT-ready", d: "Enable VAT, set rates, and keep totals consistent." },
                { t: "Offline-friendly", d: "Keep working even when the internet is down." },
                { t: "No cloud lock-in", d: "Your data stays yours, with local backups and export." },
              ].map((x) => (
                <div
                  key={x.t}
                  style={{
                    background: "#fff",
                    border: "1px solid var(--ring)",
                    borderRadius: 16,
                    padding: 16,
                    boxShadow: "0 10px 28px rgba(10,37,64,.06)",
                  }}
                >
                  <div style={{ fontWeight: 950, color: "var(--ink)" }}>{x.t}</div>
                  <p className="muted" style={{ marginTop: 6, marginBottom: 0, lineHeight: 1.6 }}>
                    {x.d}
                  </p>
                </div>
              ))}
            </div>

            <style>{`
              @media (max-width: 992px){
                .saGrid{
                  grid-template-columns: 1fr !important;
                }
              }
            `}</style>
          </div>
        </div>
      </section>

      <section className="section" style={{ paddingTop: 18, paddingBottom: 38 }}>
        <div className="container" style={{ maxWidth: 1200 }}>
          <div
            className="reveal"
            style={{
              borderRadius: 16,
              border: "1px solid var(--ring)",
              background: "#fff",
              padding: 22,
              boxShadow: "0 10px 28px rgba(10,37,64,.08)",
              position: "relative",
              overflow: "hidden",
            }}
          >
            <div
              aria-hidden
              style={{
                position: "absolute",
                inset: "-40px auto auto -40px",
                width: 180,
                height: 180,
                background: "radial-gradient(circle, rgba(33,93,99,.12), transparent 70%)",
                borderRadius: 999,
              }}
            />

            <div
              className="wooGrid"
              style={{
                display: "grid",
                gridTemplateColumns: "1.05fr .95fr",
                gap: 18,
                alignItems: "center",
              }}
            >
              <div>
                <span
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    borderRadius: 999,
                    padding: "7px 11px",
                    background: "rgba(33,93,99,.08)",
                    border: "1px solid rgba(33,93,99,.12)",
                    color: "var(--brand-700)",
                    fontWeight: 950,
                    fontSize: 11.5,
                    letterSpacing: ".03em",
                    textTransform: "uppercase",
                  }}
                >
                  WooCommerce Integration
                </span>

                <h2 className="h2" style={{ marginTop: 12, marginBottom: 0 }}>
                  For businesses that sell on WooCommerce too
                </h2>

                <p className="muted" style={{ marginTop: 10, marginBottom: 0, lineHeight: 1.7, maxWidth: 680 }}>
                  eKasiBooks is not just for manual invoicing. If you run a WooCommerce store, you can use eKasiBooks to
                  keep your business operations tighter by syncing store data into the app and managing the accounting side
                  with the same simplicity you already get for quotes, invoices, customers, and reporting.
                </p>
              </div>

              <div
                style={{
                  background: "var(--card)",
                  border: "1px solid var(--ring)",
                  borderRadius: 16,
                  padding: 16,
                  boxShadow: "0 10px 28px rgba(10,37,64,.06)",
                }}
              >
                <div style={{ fontWeight: 950, color: "var(--ink)", marginBottom: 10 }}>Why it matters</div>

                <div style={{ display: "grid", gap: 10 }}>
                  {[
                    "Great for businesses already selling through WooCommerce",
                    "Brings store activity closer to your invoicing and admin flow",
                    "Helps reduce double work between your website and desktop app",
                    "Ideal for growing businesses that want one practical system",
                  ].map((item) => (
                    <div
                      key={item}
                      style={{
                        display: "flex",
                        gap: 10,
                        alignItems: "flex-start",
                        color: "var(--ink)",
                        lineHeight: 1.55,
                        fontWeight: 700,
                      }}
                    >
                      <span style={{ color: "var(--brand)", fontWeight: 950 }}>•</span>
                      <span>{item}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            <style>{`
              @media (max-width: 992px){
                .wooGrid{
                  grid-template-columns: 1fr !important;
                }
              }
            `}</style>
          </div>
        </div>
      </section>

      <section className="section" style={{ paddingTop: 38, paddingBottom: 56 }}>
        <div className="container" style={{ maxWidth: 1200 }}>
          <h2 className="h2 center reveal">Why small businesses choose eKasiBooks</h2>
          <p className="center muted reveal" style={{ marginTop: 10, maxWidth: 820, marginInline: "auto" }}>
            Built for owners who want to invoice fast, look professional, stay in control, and connect their store
            workflows without complexity.
          </p>

          <div
            className="featuresGrid"
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(3, minmax(0,1fr))",
              gap: 16,
              marginTop: 22,
              alignItems: "stretch",
            }}
          >
            {[
              { t: "Quotes → Invoices", d: "Create quotes and convert to invoices in one click. VAT/no-VAT friendly.", i: "🧰" },
              { t: "Customers & Statements", d: "Keep customer records tidy and generate statements instantly.", i: "👥" },
              { t: "Branding & Templates", d: "Your logo, colours and templates that make you look pro.", i: "🎨" },
              { t: "Payment Tracking", d: "Record payments, see who owes you, and follow up faster.", i: "💸" },
              { t: "WooCommerce Sync", d: "Connect your WooCommerce store and keep your business workflow more connected.", i: "🛒" },
              { t: "Your data stays yours", d: "Desktop app. No forced cloud lock-in.", i: "🔒" },
            ].map((f) => (
              <div
                key={f.t}
                className="reveal cardLift"
                style={{
                  background: "#fff",
                  border: "1px solid var(--ring)",
                  borderRadius: 16,
                  padding: 18,
                  boxShadow: "0 10px 28px rgba(10,37,64,.08)",
                  height: "100%",
                }}
              >
                <h3 className="h3" style={{ marginBottom: 8 }}>
                  <span style={{ marginRight: 8 }}>{f.i}</span>
                  {f.t}
                </h3>
                <p className="muted" style={{ margin: 0, lineHeight: 1.6 }}>
                  {f.d}
                </p>
              </div>
            ))}
          </div>

          <div className="reveal" style={{ textAlign: "center", marginTop: 18 }}>
            <a
              href={links.features}
              onClick={() => {
                trackEvent("cta_click", {
                  label: "features",
                  location: "features_section",
                  page: window.location.pathname,
                });
              }}
              style={{
                display: "inline-flex",
                alignItems: "center",
                justifyContent: "center",
                borderRadius: 999,
                padding: "10px 16px",
                fontWeight: 950,
                textDecoration: "none",
                background: "var(--card)",
                border: "1px solid var(--ring)",
                color: "var(--ink)",
                boxShadow: "0 10px 24px rgba(10,37,64,.08)",
                transition: "transform .2s ease, box-shadow .2s ease",
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.transform = "translateY(-2px)";
                e.currentTarget.style.boxShadow = "0 16px 34px rgba(10,37,64,.12)";
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.transform = "translateY(0)";
                e.currentTarget.style.boxShadow = "0 10px 24px rgba(10,37,64,.08)";
              }}
            >
              Explore all features →
            </a>
          </div>

          <style>{`
            @media (max-width: 992px){
              .featuresGrid{
                grid-template-columns: 1fr !important;
              }
            }
          `}</style>
        </div>
      </section>

      <section className="section" style={{ paddingTop: 44, paddingBottom: 56 }}>
        <div className="container" style={{ maxWidth: 1200 }}>
          <h2 className="h2 center reveal">Live Preview</h2>
          <p className="center muted reveal" style={{ marginTop: 8 }}>
            Swipe through a few screens from quoting to statements.
          </p>

          <div className="reveal" style={{ marginTop: 14 }}>
            <ScreenshotSlider slides={slides} />
          </div>
        </div>
      </section>

      <section className="section" style={{ paddingTop: 44, paddingBottom: 44 }}>
        <div className="container" style={{ maxWidth: 1200 }}>
          <div
            className="reveal"
            style={{
              background: "var(--card)",
              borderRadius: 16,
              padding: 22,
              border: "1px solid var(--ring)",
              boxShadow: "0 10px 28px rgba(10,37,64,.08)",
            }}
          >
            <h3 className="h3 center" style={{ marginBottom: 14 }}>
              Get started in 3 simple steps
            </h3>

            <div
              className="stepsGrid"
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(3, minmax(0,1fr))",
                gap: 14,
              }}
            >
              {[
                { n: "1", t: "Add your business", d: "Logo, address, VAT number and defaults." },
                { n: "2", t: "Send a quote", d: "Create in seconds. Email or print beautifully." },
                { n: "3", t: "Convert & get paid", d: "Convert to invoice, record payments, send statements." },
              ].map((s) => (
                <div
                  key={s.n}
                  className="cardLift"
                  style={{
                    background: "#fff",
                    border: "1px solid var(--ring)",
                    borderRadius: 16,
                    padding: 18,
                    boxShadow: "0 10px 28px rgba(10,37,64,.08)",
                  }}
                >
                  <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                    <span
                      style={{
                        width: 30,
                        height: 30,
                        borderRadius: 999,
                        display: "inline-flex",
                        alignItems: "center",
                        justifyContent: "center",
                        fontWeight: 950,
                        color: "#fff",
                        background: "var(--brand)",
                      }}
                    >
                      {s.n}
                    </span>
                    <strong style={{ color: "var(--ink)" }}>{s.t}</strong>
                  </div>
                  <p className="muted" style={{ marginTop: 8, marginBottom: 0, lineHeight: 1.6 }}>
                    {s.d}
                  </p>
                </div>
              ))}
            </div>

            <style>{`
              @media (max-width: 992px){
                .stepsGrid{
                  grid-template-columns: 1fr !important;
                }
              }
            `}</style>
          </div>
        </div>
      </section>

      <section className="section" style={{ paddingTop: 22, paddingBottom: 44 }}>
        <div className="container" style={{ maxWidth: 1200 }}>
          <div
            className="reveal"
            style={{
              borderRadius: 16,
              border: "1px solid var(--ring)",
              background: "#fff",
              padding: 22,
              boxShadow: "0 10px 28px rgba(10,37,64,.08)",
              position: "relative",
              overflow: "hidden",
            }}
          >
            <div
              style={{
                position: "absolute",
                inset: "auto -140px -140px auto",
                width: 240,
                height: 240,
                background: "radial-gradient(circle, rgba(33,93,99,.18), transparent 70%)",
                borderRadius: 999,
              }}
            />
            <p style={{ margin: 0, fontWeight: 900, color: "var(--ink)", lineHeight: 1.5, fontSize: 16.5 }}>
              “I used to struggle with Word templates. With eKasiBooks I send quotes in 2 minutes and look legit.”
            </p>
            <p className="muted" style={{ marginTop: 8, marginBottom: 0 }}>
              – Small business owner, Pretoria
            </p>
          </div>
        </div>
      </section>

      <section className="section" style={{ paddingTop: 22, paddingBottom: 56 }}>
        <div className="container" style={{ maxWidth: 1200 }}>
          <div
            className="reveal billCard"
            style={{
              background: "var(--card)",
              borderRadius: 16,
              padding: 22,
              border: "1px solid var(--ring)",
              boxShadow: "0 10px 28px rgba(10,37,64,.08)",
              transition: "transform .25s ease, box-shadow .25s ease",
            }}
          >
            <div
              className="billGrid"
              style={{
                display: "grid",
                gridTemplateColumns: "1.2fr .8fr",
                gap: 16,
                alignItems: "center",
              }}
            >
              <div>
                <h3 className="h3" style={{ marginBottom: 8 }}>
                  Simple pricing
                </h3>
                <p className="muted" style={{ margin: 0, lineHeight: 1.6 }}>
                  Start your free trial today. Upgrade when you’re ready to grow — including if you need WooCommerce
                  integration for your store workflow.
                </p>
              </div>

              <div style={{ display: "flex", gap: 10, justifyContent: "flex-end", flexWrap: "wrap" }}>
                <a
                  href={links.pricing}
                  onClick={() => {
                    trackEvent("cta_click", {
                      label: "pricing",
                      location: "pricing_section",
                      page: window.location.pathname,
                    });
                  }}
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    justifyContent: "center",
                    borderRadius: 999,
                    padding: "10px 16px",
                    fontWeight: 950,
                    textDecoration: "none",
                    background: "#fff",
                    color: "var(--ink)",
                    border: "1px solid var(--ring)",
                    transition: "transform .2s ease, box-shadow .2s ease",
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.transform = "translateY(-2px)";
                    e.currentTarget.style.boxShadow = "0 16px 34px rgba(10,37,64,.12)";
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.transform = "translateY(0)";
                    e.currentTarget.style.boxShadow = "none";
                  }}
                >
                  See Pricing
                </a>

                <a
                  href={links.portalRegister}
                  onClick={() => {
                    trackEvent("cta_click", {
                      label: "register",
                      location: "pricing_section",
                      page: window.location.pathname,
                    });
                  }}
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    justifyContent: "center",
                    borderRadius: 999,
                    padding: "10px 16px",
                    fontWeight: 950,
                    textDecoration: "none",
                    background: "var(--brand)",
                    color: "#fff",
                    transition: "transform .2s ease, box-shadow .2s ease",
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.transform = "translateY(-2px)";
                    e.currentTarget.style.boxShadow = "0 16px 34px rgba(10,37,64,.12)";
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.transform = "translateY(0)";
                    e.currentTarget.style.boxShadow = "none";
                  }}
                >
                  Create Free Account
                </a>
              </div>
            </div>

            <style>{`
              @media (max-width: 992px){
                .billGrid{
                  grid-template-columns: 1fr !important;
                }
              }
            `}</style>
          </div>
        </div>
      </section>

      <section className="section" style={{ paddingTop: 22, paddingBottom: 72 }}>
        <div className="container" style={{ maxWidth: 1200 }}>
          <h2 className="h2 center reveal">Questions, answered</h2>

          <div
            className="faqGrid reveal"
            style={{
              display: "grid",
              gridTemplateColumns: "1fr 1fr",
              gap: 18,
              marginTop: 14,
            }}
          >
            <div
              className="cardLift"
              style={{
                background: "#fff",
                border: "1px solid var(--ring)",
                borderRadius: 16,
                padding: 18,
                boxShadow: "0 10px 28px rgba(10,37,64,.08)",
              }}
            >
              <details>
                <summary>Does it work offline?</summary>
                <p>
                  Yes — once you&#39;re signed in, you can quote and invoice without internet. You&#39;ll need a connection
                  to sign in again if you log out.
                </p>
              </details>
              <details>
                <summary>Do you support VAT?</summary>
                <p>Enable VAT, pick your rate, and totals are calculated automatically.</p>
              </details>
              <details>
                <summary>Do you support WooCommerce?</summary>
                <p>
                  Yes — eKasiBooks includes WooCommerce integration for businesses that want their online store workflow
                  connected to the app.
                </p>
              </details>
            </div>

            <div
              className="cardLift"
              style={{
                background: "#fff",
                border: "1px solid var(--ring)",
                borderRadius: 16,
                padding: 18,
                boxShadow: "0 10px 28px rgba(10,37,64,.08)",
              }}
            >
              <details>
                <summary>Can I use my logo &amp; colours?</summary>
                <p>Absolutely. Upload your logo and choose templates to match your brand.</p>
              </details>
              <details>
                <summary>How do I backup?</summary>
                <p>Use the built-in backup to export a safe copy of your data anytime.</p>
              </details>
              <details>
                <summary>Is it only for offline businesses?</summary>
                <p>
                  No. eKasiBooks works well for service businesses, traders, and businesses that also sell through a
                  WooCommerce website.
                </p>
              </details>
            </div>
          </div>

          <style>{`
            @media (max-width: 992px){
              .faqGrid{
                grid-template-columns: 1fr !important;
              }
            }
            details { margin-top: 10px; }
            details:first-of-type { margin-top: 0; }
            details > summary { padding: 12px 14px; cursor: pointer; font-weight: 900; list-style: none; }
            details > summary::-webkit-details-marker { display: none; }
            details > summary:before {
              content: "▸";
              display: inline-block;
              margin-right: 10px;
              transform: translateY(-1px);
              transition: transform .2s ease;
              color: var(--brand);
              font-weight: 950;
            }
            details[open] > summary:before { transform: rotate(90deg) translateY(-1px); }
            details p { margin: 10px 0 0; padding: 0 14px 14px; color: var(--muted); line-height: 1.6; }
          `}</style>
        </div>
      </section>

      <section className="section" style={{ paddingTop: 0, paddingBottom: 56 }}>
        <div className="container" style={{ maxWidth: 1200 }}>
          <div
            className="reveal"
            style={{
              borderRadius: 16,
              border: "1px solid var(--ring)",
              background: "var(--card)",
              padding: 22,
              boxShadow: "0 10px 28px rgba(10,37,64,.08)",
              textAlign: "center",
            }}
          >
            <h3 className="h3" style={{ marginBottom: 8 }}>
              Ready to look professional and get paid faster?
            </h3>

            <div style={{ display: "flex", justifyContent: "center", gap: 10, flexWrap: "wrap", marginTop: 10 }}>
              <a
                href={links.portalRegister}
                onClick={() => {
                  trackEvent("cta_click", {
                    label: "register",
                    location: "final_cta",
                    page: window.location.pathname,
                  });
                }}
                style={{
                  borderRadius: 999,
                  padding: "10px 18px",
                  fontWeight: 950,
                  textDecoration: "none",
                  background: "var(--brand)",
                  color: "#fff",
                  transition: "transform .2s ease, box-shadow .2s ease",
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.transform = "translateY(-2px)";
                  e.currentTarget.style.boxShadow = "0 16px 34px rgba(10,37,64,.12)";
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.transform = "translateY(0)";
                  e.currentTarget.style.boxShadow = "none";
                }}
              >
                Create Free Account
              </a>

              <a
                href={links.download}
                onClick={() => {
                  trackEvent("cta_click", {
                    label: "download",
                    location: "final_cta_secondary",
                    page: window.location.pathname,
                  });
                }}
                style={{
                  borderRadius: 999,
                  padding: "10px 18px",
                  fontWeight: 950,
                  textDecoration: "none",
                  background: "#fff",
                  color: "var(--ink)",
                  border: "1px solid var(--ring)",
                  transition: "transform .2s ease, box-shadow .2s ease",
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.transform = "translateY(-2px)";
                  e.currentTarget.style.boxShadow = "0 16px 34px rgba(10,37,64,.12)";
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.transform = "translateY(0)";
                  e.currentTarget.style.boxShadow = "none";
                }}
              >
                Download App
              </a>
            </div>
          </div>
        </div>
      </section>

      <style>{`
        .reveal{
          opacity: 0;
          transform: translateY(20px);
          transition: all .6s ease;
        }
        .reveal.show{
          opacity: 1;
          transform: translateY(0);
        }
        .cardLift{
          transition: transform .25s ease, box-shadow .25s ease;
        }
        .cardLift:hover{
          transform: translateY(-4px);
          box-shadow: 0 18px 40px rgba(10,37,64,.12);
        }
        .billCard:hover{
          transform: translateY(-4px);
          box-shadow: 0 18px 40px rgba(10,37,64,.12);
        }
        @keyframes zoomFade {
          from { opacity: 0; }
          to { opacity: 1; }
        }
      `}</style>

      <StickyCta
        primaryHref={links.portalRegister}
        primaryLabel="Create Free Account"
        secondaryHref={links.download}
        secondaryLabel="Download App"
      />
    </main>
  );
}